name: OPA unit tests
on: [push, pull_request]

jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👇 Pin OPA to a 0.x release (pre-1.0 syntax)
      - name: Install OPA
        uses: open-policy-agent/setup-opa@v1
        with:
          version: v0.63.0
          
      - name: Run OPA unit tests
        run: |
         opa version
         opa test -v policy/

