name: Step 5.2 OPA Unit Tests Only

on:
  workflow_dispatch:
  push:
    paths:
      - 'policy/**'

jobs:
  opa-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OPA
        run: |
         curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
         chmod +x opa
         sudo mv opa /usr/local/bin/

      - name: Run OPA unit tests
        run: opa test policy/
