name: Step 5.2 - OPA Tests Only

on:
  push:
    paths:
      - 'policy/require_tags.rego'
      - 'policy/require_tags_test.rego'

jobs:
  opa-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Run OPA Unit Tests
        run: opa test policy/
