name: Terraform + Conftest Lab

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.tf'
      - '.github/workflows/lab.yml'

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_$(uname -s)_$(uname -m).tar.gz
          tar xzf conftest_$(uname -s)_$(uname -m).tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Create dummy Terraform config
        run: |
          rm -rf terraform-test
          mkdir terraform-test
          cat > terraform-test/main.tf <<EOF
          terraform {
            required_version = ">= 1.0"
          }
          resource "null_resource" "example" {}
          EOF

      - name: Terraform Init & Plan
        run: |
          cd terraform-test
          terraform init -input=false
          terraform plan -out=tfplan

      - name: Export plan to JSON
        run: |
          cd terraform-test
          terraform show -json tfplan > tfplan.json

      - name: Conftest Policy Check
        run: conftest test terraform-test/tfplan.json
