name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: go install github.com/open-policy-agent/conftest@latest

      # Dummy Terraform
      - run: mkdir terraform-test
      - run: |
          cat <<EOF > terraform-test/main.tf
          terraform {
            required_version = ">= 1.7.5"
          }

          provider "null" {}

          resource "null_resource" "example" {
            provisioner "local-exec" {
              command = "echo 'Hello Policy Check'"
            }
          }
          EOF

      # Run Terraform plan
      - run: cd terraform-test && terraform init && terraform plan -out=tfplan
      - run: cd terraform-test && terraform show -json tfplan > tfplan.json

      # Inject environment tag into plan JSON
      - run: jq '.resource_changes[].change.after |= . + {tags: {environment: "dev"}}' terraform-test/tfplan.json > terraform-test/tfplan_tagged.json

      # Conftest check
      - run: conftest test terraform-test/tfplan_tagged.json

      # OPA Unit Tests
      - name: Run OPA unit tests
        run: opa test policy/
