name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: go install github.com/open-policy-agent/conftest@latest

      - uses: open-policy-agent/setup-opa@v1

      # Terraform init & plan
      - run: cd terraform-test && terraform init && terraform plan -out=tfplan

      # Convert plan to JSON
      - run: cd terraform-test && terraform show -json tfplan > tfplan.json

      # Inject tags so policy passes
      - run: jq '.resource_changes[].change.after.tags = {"environment":"dev"}' terraform-test/tfplan.json > terraform-test/tfplan_tagged.json

      # Policy check
      - name: Conftest Policy Check
        run: conftest test terraform-test/tfplan_tagged.json

      # OPA unit tests
      - name: Run OPA Unit Tests
        run: opa test policy/
