name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install conftest
        run: go install github.com/open-policy-agent/conftest@latest

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Create dummy Terraform config
        run: |
          mkdir -p terraform-test
          cat <<EOF > terraform-test/main.tf
          terraform {
            required_version = ">= 1.7.5"
          }

          provider "null" {}

          resource "null_resource" "example" {
            triggers = {
              environment = "dev"
            }
            provisioner "local-exec" {
              command = "echo 'Hello Policy Check'"
            }
          }
          EOF

      - name: Terraform Init & Plan
        run: cd terraform-test && terraform init && terraform plan -out=tfplan

      - name: Export plan to JSON
        run: cd terraform-test && terraform show -json tfplan > tfplan.json

      - name: Conftest Policy Check
        run: conftest test terraform-test/tfplan.json

      - name: Run OPA Unit Tests
        run: opa test policy/
