name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Install Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # Install Go (needed for conftest)
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Install conftest
      - run: go install github.com/open-policy-agent/conftest@latest

      # Install OPA CLI
      - run: curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64 && chmod +x opa && sudo mv opa /usr/local/bin/

      # Terraform plan
      - run: cd terraform-test && terraform init && terraform plan -out=tfplan

      # Export tfplan to JSON
      - run: cd terraform-test && terraform show -json tfplan > tfplan.json

      # Inject tags into tfplan.json for testing
      - run: cd terraform-test && jq '.resource_changes[].change.after.tags = {"environment":"dev"}' tfplan.json > tfplan_tagged.json

      # Conftest policy check (Step 5.1)
      - name: Conftest Policy Check
        run: conftest test terraform-test/tfplan_tagged.json

      # OPA unit tests for Rego policies (Step 5.2)
      - name: Run OPA Unit Tests
        run: opa test policy/
