name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # Install Go (needed for conftest)
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Install conftest
      - run: go install github.com/open-policy-agent/conftest@latest

      # Passing example
      - name: Run policy check - PASS case
        run: |
          cd terraform-test
          terraform init -input=false
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json
          conftest test tfplan.json --policy ../policy

      # Failing example
      - name: Run policy check - FAIL case (expected)
        run: |
          cd terraform-fail
          terraform init -input=false
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json
          conftest test tfplan.json --policy ../policy || true

      # Run OPA unit tests for Rego policies
      - name: Run OPA unit tests
        run: opa test policy/

