name: Policy Check
on:
  push:
  pull_request:

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install conftest
        run: go install github.com/open-policy-agent/conftest@latest

      - name: Create dummy Terraform config
        run: |
          mkdir -p terraform-test
          cat > terraform-test/main.tf <<'EOT'
          terraform {
            required_version = ">= 1.7.5"
          }

          provider "null" {}

          resource "null_resource" "example" {
            provisioner "local-exec" {
              command = "echo Hello Policy Check"
            }
          }
          EOT

      - name: Terraform Init & Plan
        run: |
          cd terraform-test
          terraform init
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Conftest Policy Check
        run: echo "Dummy conftest check"
