name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install OPA CLI for Rego unit tests
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      # Run OPA Unit Tests (this is Step 5.2 screenshot)
      - name: Run OPA Unit Tests
        run: opa test policy/
