name: Policy Check
on: [push, pull_request]

jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # Install Go (needed for conftest)
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Install conftest
      - name: Install conftest
        run: go install github.com/open-policy-agent/conftest@latest

      # Create dummy Terraform config (safe & quick)
      - name: Create dummy Terraform config
        run: |
          mkdir -p terraform-test
          cat <<EOF > terraform-test/main.tf
          terraform {
            required_version = ">= 1.7.5"
          }

          provider "null" {}

          resource "null_resource" "example" {
            provisioner "local-exec" {
              command = "echo 'Hello Policy Check'"
            }
          }
          EOF

      # Terraform Init & Plan
      - name: Terraform Init & Plan
        run: |
          cd terraform-test
          terraform init
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      # Conftest Policy Check
      - name: Conftest Policy Check
        run: conftest test terraform-test/tfplan.json

      # Run OPA Unit Tests for Rego policies
      - name: Run OPA Unit Tests
        run: opa test policy/
